BotSelfConfig:
  host: "127.0.0.1"
  port: 8080
  debug: true
  superusers: [ "21778445" ]
  nickname: [ "ATRI", "Atri", "atri", "亚托莉", "アトリ" ]
  command_start: [ "", "/" ]
  command_sep: [ "." ]
  session_expire_timeout: 60
  proxy: ""  # 请参考文档

InlineGoCQHTTP:
  enabled: true
  accounts: # 可多个账号，具体请参考文档
    - uin: 3186471283
      password: ""
      protocol: 5

  download_domain: "github.com"
  download_version: "v1.0.0-rc4"

SauceNAO:
  key: "5886242cbae954452781f44279916ffcf9b940fc"
